name: Test Execution

on:
  push:
    branches: [ master, main ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'corretto'
          cache: maven

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests without API key
        if: github.event_name == 'push'
        run: mvn test -Punit-test -Dtest=ReplicateAutoConfigTestWithoutApiKey


      - name: Run remaining unit tests
        if: github.event_name == 'push'
        env:
          REPLICATE_API_KEY: ${{ secrets.REPLICATE_API_KEY }}
        run: mvn test -Punit-test -Dtest=!ReplicateAutoConfigTestWithoutApiKey

      - name: Run all tests except ReplicateAutoConfigTestWithoutApiKey
        if: github.event_name == 'workflow_dispatch'
        env:
          REPLICATE_API_KEY: ${{ secrets.REPLICATE_API_KEY }}
        run: mvn verify -Dtest=!ReplicateAutoConfigTestWithoutApiKey -DfailIfNoTests=false jacoco:report

      - name: SonarCloud Scan
        if: github.event_name == 'workflow_dispatch' && success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          mvn sonar:sonar
          -Dsonar.organization=nilsw13
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.projectKey=nilsw13_Spring-Boot-Replicate
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml